---

- hosts: localhost
  tasks:
    - name: Download minio
      shell:
        cmd: wget --no-check-certificate -O /tmp/minio https://ipfs.subutai.io/ipfs/QmeXNznhTNiHK7mjLMMQ8i5ojiHjAPdThAfX8tFiMtUSFt/minio

- hosts: all
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: copy minio binary
      copy:
        src: /tmp/minio
        dest: /usr/local/bin/minio
        mode: 777    

    - name: copy minio service file
      template:
        src: minio.service
        dest: /etc/systemd/system/minio.service
        mode: 0644

    - name: copy default minio
      template:
        src: myhosts.j2 
        dest: /etc/default/minio

    - name: systemd reload
      systemd:
         daemon_reload: yes
         
    - name: start and enable minio service
      systemd:	
        name: minio	
        state: started	
        enabled: yes
