---

- hosts: localhost
  tasks:

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Download foo.conf
      shell:
        cmd: wget --no-check-certificate -O /tmp/test/minio https://dl.min.io/server/minio/release/linux-amd64/minio

- hosts: all
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: copy minio binary
      copy:
        src: /tmp/test/minio
        dest: /usr/local/bin/minio
        mode: 777    

    - name: copy minio service file
      template:
        src: minio.service
        dest: /etc/systemd/system/minio.service
        mode: 0644

    - name: copy default minio
      template:
        src: myhosts.j2 
        dest: /etc/default/minio

    - name: systemd reload
      systemd:
         daemon_reload: yes


    - name: start minio
      systemd:
        name: minio
        state: started
        enabled: yes

